<title><?php echo !empty($this->placeholder('layout')->pageTitle) ? $this->placeholder('layout')->pageTitle : 'Djordje Mandaric resume';?></title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" type="text/css" href="/public/stylesheets/main.css" />
<script type="text/javascript" src="/public/javascript/jquery-1.8.3.min.js"></script>
<?php echo $this->headLink();?>
<?php echo $this->headScript();?>